### ISSUE TITLE
Investigate packageinfo.vdf

### ISSUE THREAD

**Issue by leovp** [leovp/steamfiles#3]
Is there any useful data in there at all?
Does it make sense to support it in `steamfiles` library?
How much does the format differ from appinfo.vdf?

**Comment by leovp** [comment]
Results of an investigation:
1. Doesn't really matter, let's parse it!
2. Yes, it makes sense to support everything.
3. They appear to have different VDF_VERSION (first 4 bytes). After that, who knows.

**Comment by c12h** [comment]
As far as I can tell, packageinfo.vdf has a format much like appinfo.vdf: an 8-byte header, then sections that start with a 4-byte integer ID, then a 4-byte integer that specifies end-of-file. As with appinfo, the sections are not padded and so are not aligned.

For packageinfo.vdf, the terminating ID # is -1 (instead of 0 for appinfo.vdf). Each section consists of the ID, 24 bytes whose purpose I do not know and then the VDF values in binary form.

**Comment by CTimmerman** [comment]
Looks like a bunch of arrays, strings, and integers, according to https://github.com/Theo47/depressurizer/blob/master/Depressurizer/VdfFile/VdfFileNode.cs

**Comment by leovp** [comment]
@c12h 
@CTimmerman 
Thank you very much!
I'll start implementing packageinfo support soon.

**Comment by CTimmerman** [comment]
You're welcome. Here's a Python lib that appears to parse binary VDFs: https://github.com/barneygale/bvdf/blob/master/bvdf.py
