### ISSUE TITLE
Can't parse VDF_VERSION 0x07564427

### ISSUE THREAD

**Issue by kijdam** [leovp/steamfiles#5]
Hi,

steamfiles seems to be a cool lib, congrats.

However it seems it doesn't handle recent VDF_VERSION.

I got this message when I try to parse my current appinfo.vdf:

```
raise ValueError('Unknown VDF_VERSION: 0x{0:08x}'.format(header['version']))
ValueError: Unknown VDF_VERSION: 0x07564427
```

Is this easily fixable ?
Thanks for your help!

**Comment by NullSoldier** [comment]
Can you paste your appinfo.vdf into haste bin and paste a link here? You provided no reproduction case so it's very hard to fix.

**Comment by EhsanKia** [comment]
I got the same issue trying to parse appinfo.vdf
I'm pretty sure this applies to all appinfos, but if you still can't reproduce on yours, I Can upload mine.

**Comment by NullSoldier** [comment]
Please upload it and we can give it a shot unless you want to fix it
yourself.

**Comment by EhsanKia** [comment]
Found some info about it online:

From [SteamEdit](http://steamedit.tg-software.com/):
`appinfo.vdf 0x07564427 (Introduced early January 2017).`

And from some forum thread:
`the file now starts with 0x07564427 instead of 0x07564426 and each app info is formed of a single KVS instead of 1 KVS per info section ...`

Here's mine: https://drive.google.com/file/d/0B0mnh0chJK1RaTJ0MDdkTzZtVGM/view?usp=sharing

**Comment by kijdam** [comment]
Yes I read the same info too :)

Here is mine, for science.

[appinfo.zip](https://github.com/leovp/steamfiles/files/1202929/appinfo.zip)

**Comment by arboliveira** [comment]
https://github.com/arboliveira/steamside/commit/b6cf4aa09196ec0632529e065f6303dda8fc4e86

**Comment by EhsanKia** [comment]
I ended up installing from master, but a pip version bump would be nice since this is a pretty big update and appinfo straight up doesn't work with new appinfo.vdf version without this change! Cheers and thanks for fixing this :)
